### ISSUE TITLE
Raise more useful API errors

### ISSUE THREAD

**Issue by jacobtomlinson** [kr8s-org/kr8s#118]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

When we get an error from Kubernetes and we've exhausted various mitigations such as authentication we simply raise the exception up to the user.

https://github.com/kr8s-org/kr8s/blob/7bfe38779dde36660b70fc6c943bbb62b51e0e5f/kr8s/_api.py#L150

However the `response.json()` contains more useful information on what caused the error. We should include this in the exception before we raise it up.

**Comment by jacksgt** [comment]
Very important for usability indeed! I just bumped into this myself.
It's quite hard to understand what's wrong with a complicated Deployment spec when all you have is a `400 Bad Request`.
