### ISSUE TITLE
Possible copy-paste error in license/docs attribution?

### ISSUE THREAD

**Issue by jcrist** [kr8s-org/kr8s#157]
### Which project are you reporting a bug for?

kr8s

### What happened?

Hi Jacob :wave:, nice project! While poking through the docs and source, I noticed two locations where the author attribution looks like a potential copy-paste error (ported over from dask-kubernetes).

- [LICENSE](https://github.com/kr8s-org/kr8s/blob/c4d9f71c54c06f2c4541b17daf88409d80001bcb/LICENSE#L3)
- [docs/conf.py](https://github.com/kr8s-org/kr8s/blob/c4d9f71c54c06f2c4541b17daf88409d80001bcb/docs/conf.py#L14)

Not sure if these are correct or not, but figured I'd raise an issue to check.

*(edit: looking through more of the source, I'm now guessing this attribution was intentional, possibly to cite code copied out of dask-kubernetes? If so, apologies for the noise)*

**Comment by jacobtomlinson** [comment]
Hey @jcrist! Yup this is intentional as the foundation of this repo was pulled from Dask-Kubernetes.

**Comment by jcrist** [comment]
Makes sense, sorry for the noise.

**Comment by jacobtomlinson** [comment]
No worries at all!
