### ISSUE TITLE
Support kubeconfig contexts for authentication

### ISSUE THREAD

**Issue by jeefberkey** [kr8s-org/kr8s#158]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

I have many kubernetes clusters in my kubeconfig, and would like this tool to use a different context if I ask it to, without having to switch to the context on my system.

For my use case, I'm using python to determine which context to operate on.

Example from the official lib: https://github.com/kubernetes-client/python/blob/master/examples/multiple_clusters.py#L40

**Comment by jacobtomlinson** [comment]
Yeah great idea, we should add a `context` kwarg to the `api()` constructor which is passed to the `KubeAuth` class to allow overriding the current context. 

```python
import kr8s

api = kr8s.api(context="my-awesome-cluster")
version = api.version()
print(version)  # Prints out the version information from the Kubernetes cluster specified in the my-awesome-cluster context
```

Right now we either use the current context, or if that's not set the first one.

https://github.com/kr8s-org/kr8s/blob/c4d9f71c54c06f2c4541b17daf88409d80001bcb/kr8s/_auth.py#L90-L97

**Comment by jeefberkey** [comment]
Fantastic, thank you. I was thinking about trying to do this myself tonight but you beat me to it! (and probably did it better)
