### ISSUE TITLE
How can I exec into a pod or get logs?

### ISSUE THREAD

**Issue by bigg01** [kr8s-org/kr8s#168]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

It would be quite cool to do:
- exec
- logs

**Comment by jacobtomlinson** [comment]
Logs is already implemented. You can do `pod.logs()`. 

https://docs.kr8s.org/en/latest/object.html#methods

Exec is still on the roadmap.

**Comment by jacobtomlinson** [comment]
I've opened #169 to track adding exec.
