### ISSUE TITLE
kubeconfig insecure-skip-tls-verify option is ignored when using user-token-based authentication

### ISSUE THREAD

**Issue by gazzar** [kr8s-org/kr8s#178]
### Which project are you reporting a bug for?

kr8s

### What happened?

I think this is an authentication bug, but it may be my misunderstanding. Regardless, kr8s behaves differently to kubectl.

In my development environment, my kubeconfig file sets the insecure-skip-tls-verify flag and uses a pregenerated token:
```clusters:
- name: clustername
  cluster:
    insecure-skip-tls-verify: true
    server: https://myserverurl:6443
```

With this set, I can retrieve pods for example with
`kubectl --kubeconfig=kubeconfig get pods --namespace=mynamespace --context=mycontext`

but with kr8s I get a traceback. Here are the last few lines:
```
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 159, in _connect
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 78, in start_tls
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 125, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/usr/local/lib/python3.11/site-packages/anyio/streams/tls.py", line 133, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
```

If I force line 80 of _api.py
https://github.com/kr8s-org/kr8s/blob/bd6c31d9881f4217ecdd772279d2bbbf235fa52c/kr8s/_api.py#L80
to return False, which is what I expect the call to ssl_context() to return, things work as expected

I think the ssl_context() method
https://github.com/kr8s-org/kr8s/blob/bd6c31d9881f4217ecdd772279d2bbbf235fa52c/kr8s/_auth.py#L67-L74
should be checking self.token, but I don't know the correct logic or I'm misunderstanding.

**Comment by jacobtomlinson** [comment]
Thanks for raising this @gazzar! You're right we should support disabling TLS, this is isn't implemented currently.

I've opened https://github.com/kr8s-org/kr8s/pull/180 to add this. Please feel free to give it a go and let me know if this fixes things for you.

**Comment by gazzar** [comment]
Thanks so much @jacobtomlinson for the quick response and fix, which indeed respects the insecure-skip-tls-verify flag now! Kudos!

**Comment by rkschamer** [comment]
Great! Thank you so much! 👍
