### ISSUE TITLE
Multi context/cluster querying

### ISSUE THREAD

**Issue by icosamuel** [kr8s-org/kr8s#181]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

It would be really nice to have multi-cluster querying integrated in this library. For example I'd like to be able to craft compact yet complex queries to fetch rich datasets quickly.
Here's a few ideas of what it could look like:
- `kr8s.clusters(["c1a", "c1b", "c2a"]).get('nodes')` 
- `kr8s.clusters("^c1.*$").get('nodes')`
- `kr8s.all_clusters().get('nodes')`

**Comment by jacobtomlinson** [comment]
This is a really interesting idea. Looking at your suggestions I would assume something like `kr8s.clusters()` would return a list, so then calling `.get` on that may confuse folks.

Right now I would do something explicit with API client objects like this to achieve what you are trying to do:

```python
import kr8s

nodes = []
for context in ["c1a", "c1b", "c2a"]:
    nodes += kr8s.api(context=context).get("nodes")
```

This works today.

There isn't a way currently to do "all clusters" but we could totally add the ability to pass a list to `kr8s.api`'s context kwarg and have it return an iterable of clients.

```python
import kr8s

nodes = []
for cluster in kr8s.api(context=["c1a", "c1b", "c2a"]):
    nodes += cluster.get("nodes")
```

We could also reuse the `kr8s.ALL` const that we use to specify all namespaces to allow you to iterate over all contexts.

```python
import kr8s

nodes = []
for client in kr8s.api(context=kr8s.ALL):
    nodes += client.get("nodes")
```

**Comment by jacobtomlinson** [comment]
I've thought about this some more and I worry that making the `Api` client aware of multiple clusters would just be a huge can of worms. If people want to query across multiple clusters I recommend creating a separate client for each one.

```python
import kr8s

clusters =  [kr8s.api(context=context) for context in ["c1a", "c1b", "c2a"]]
nodes = []
for cluster in clusters:
    nodes += clusters.get("nodes")
```

In the future #335 could also give us a way to get a list of contexts programatically instead of hard coding them.
