### ISSUE TITLE
Support operating on specific API versions

### ISSUE THREAD

**Issue by jcmcken** [kr8s-org/kr8s#196]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

It's not clear from the documentation how to do this, and I'm also not seeing in the code where I would hook into this functionality:

Many different API namespaces implement similarly named resources. For example, Istio has ``gateway.v1beta1.networking.istio.io`` or ``gateway.networking.istio.io`` (i.e. the ``Gateway`` object). Kubernetes also has its own ``Gateway`` in ``gateway.v1alpha1.networking.x-k8s.io`` (or ``gateway.networking.x-k8s.io``). In ``kubectl``, for example, it will pick one of these kinds if there are multiple kinds with the same name. So if you do ``kubectl get gateways``, it may return the Kubernetes gateways only or the Istio gateways only (I don't actually know how it picks).  To pick a specific API version with ``kubectl``, you can do ``kubectl get gateway.v1beta1.networking.istio.io`` or ``kubectl get gateway.networking.istio.io``. 

I think ``kr8s.get`` (and I guess other CRUD implementations) should also support this concept. For example if you have a Kubernetes Gateway named ``foo`` and an Istio Gateway named ``foo``, this is perfectly legal to do since they are different API versions.

**Comment by jacobtomlinson** [comment]
In theory this should be supported today. If something is not working then this is probably a bug. Could you share a code example of what you are trying to do and how it is not working?
