### ISSUE TITLE
how to auth with client.authentication.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by raybellwaves** [kr8s-org/kr8s#206]
Thanks for this package! I tried it today for the first time and may come back to this as I dig a bit more.

I would try to auth using

```
import kr8s
client = kr8s.api()
```

and I got

```
File /opt/userenvs/ray.bell/dsutils/lib/python3.10/site-packages/kr8s/_auth.py:139, in KubeAuth._load_kubeconfig(self)
    134 if "exec" in self._user:
    135     if (
    136         self._user["exec"]["apiVersion"]
    137         != "client.authentication.k8s.io/v1beta1"
    138     ):
--> 139         raise ValueError(
    140             "Only client.authentication.k8s.io/v1beta1 is supported for exec auth"
    141         )
    142     command = self._user["exec"]["command"]
    143     args = self._user["exec"].get("args") or []
```

Look at my ~/.kube/config file I see

users:
- name: arn:aws:eks:REGION:ACCOUNT:cluster/CLUSTERNAME
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1

Would I need to do something seperate to auth for this?

Thanks,Ray

**Comment by jacobtomlinson** [comment]
The `client.authentication.k8s.io/v1alpha1` is no longer supported in many clients. I also wouldn't expect EKS to be issuing those credentials any more.

The first thing I would try is to make sure you have the latest version of the `aws` CLI and then update your credentials.

```bash
aws eks update-kubeconfig --name mycluster 
```

If that still issues you with `v1alpha1` credentials then you could try manually changing the version in your config as `v1beta1` is probably going to be backward compatible for the ways that EKS uses it.

```bash
sed -i .bak -e 's/v1alpha1/v1beta1/' ~/.kube/config
```

Let me know how you get on!
