### ISSUE TITLE
Resource wait remains blocked when jsonpath's value is not a string

### ISSUE THREAD

**Issue by yashgorana** [kr8s-org/kr8s#297]
### Which project are you reporting a bug for?

kr8s

### What happened?

`resource.wait("jsonpath='{expression}'=value")` doesn't return when the `value` is an integer

#### Repro Code
```python
import kr8s
from kr8s.objects import StatefulSet

client = kr8s.api()
ss = StatefulSet(
    {
        "metadata": {
            "name": "test",
        },
        "spec": {
            "replicas": 3,
            "selector": {
                "matchLabels": {
                    "app": "test",
                }
            },
            "template": {
                "metadata": {
                    "labels": {
                        "app": "test",
                    }
                },
                "spec": {
                    "containers": [
                        {
                            "name": "test",
                            "image": "nginx:latest",
                        }
                    ]
                },
            },
        },
    }
)
ss.create()
ss.wait("jsonpath='{.status.availableReplicas}'=3")
```

### Anything else?

The resource YAML may have integer or boolean values, while the regex extracted value is always a string. A potential fix would be to convert the YAML value to string?

![image](https://github.com/kr8s-org/kr8s/assets/11070218/9cd75517-f566-454d-8442-b0afd0869ea7)

**Comment by jacobtomlinson** [comment]
Appreciate the well written reproducer! Made it easy for me to copy as a test and fix it up. Things should be good now with #300.

**Comment by jacobtomlinson** [comment]
`v0.13.1` is out containing this fix
