### ISSUE TITLE
Add CI for kubectl-ng

### ISSUE THREAD

**Issue by jacobtomlinson** [kr8s-org/kr8s#3]
Currently only testing `kr8s` in GitHub Actions. Would be good to add another workflow to test `kubectl-ng`.

**Comment by djmattyg007** [comment]
What is the relationship between kr8s and kubectl-ng?

**Comment by jacobtomlinson** [comment]
@djmattyg007  `kubectl-ng` is a toy example for demo purposes right now. It's a reimplementation of `kubectl` using `kr8s`. It's mostly for fun but building it alongside `kr8s` has helped keep aligned with the goal of feeling familiar with `kubectl` and add features and utilities to `kr8s` by pushing them upstream after implementing them in `kubectl-ng`. It's also helped me learn a load about the Kubernetes API and how `kubectl` interacts with it.
