### ISSUE TITLE
Error when portforwarding

### ISSUE THREAD

**Issue by declark1** [kr8s-org/kr8s#308]
### Which project are you reporting a bug for?

kr8s

### What happened?

When I portforward a pod using the context manager or thread, it works fine, but I get the following RuntimeError after using it:

```
Task exception was never retrieved
future: <Task finished name='Task-23' coro=<PortForward._sync_sockets() done, defined at /Users/dan/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kr8s/_portforward.py:215> exception=RuntimeError("generator didn't stop")>
Traceback (most recent call last):
  File "/Users/dan/.pyenv/versions/3.11.4/lib/python3.11/site-packages/kr8s/_portforward.py", line 218, in _sync_sockets
    async with self._connect_websocket() as ws:
  File "/Users/dan/.pyenv/versions/3.11.4/lib/python3.11/contextlib.py", line 215, in __aexit__
    raise RuntimeError("generator didn't stop")
RuntimeError: generator didn't stop
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x103280490>
```

**Comment by jacobtomlinson** [comment]
Please can you provide a [minimal bug report](https://matthewrocklin.com/minimal-bug-reports) with a reproducible code example (that I can ideally copy/paste) do that I can debug this issue?

**Comment by beanagrammer** [comment]
Hi, I was able to reproduce the same error by looping through pods for multiple portforwarding. @jacobtomlinson 

```
api = kr8s.api()
all_pods = [
    api.get("pods", namespace=name1),
    api.get("pods", namespace=name2),
    api.get("pods", namespace=name3),
]

for pods in all_pods:
    print(pods)
    pf = pods[0].portforward(remote_port=5432, local_port=9090)
    pf.start()
    psql = DB()
    print("port forwarded", psql)
    pf.stop()

```

```
port forwarded <db.DB object at 0x105b5d6a0>
port forwarded <db.DB object at 0x105b5e000>
Unhandled exception in client_connected_cb
transport: <_SelectorSocketTransport closed fd=14>
Traceback (most recent call last):
  File "/Users/krconnectlena/Work/dataEng/wauBatch/.venv/lib/python3.12/site-packages/kr8s/_portforward.py", line 218, in _sync_sockets
    async with self._connect_websocket() as ws:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 222, in __aexit__
    raise RuntimeError("generator didn't stop")
RuntimeError: generator didn't stop
port forwarded <db.DB object at 0x105b28350>
```

**Comment by beanagrammer** [comment]
I was able to track the down the issue for my case. 

After successful ws connection has been made, it does not break out of the loop which causes continuous code execution in _connect_websocket().
`.venv/lib/python3.12/site-packages/kr8s/_portforward.py`
```
    async def _connect_websocket(self) -> None:
        """Connect to the Kubernetes portforward websocket."""
        connection_attempts = 0
        while True:
            if not self.pod:
                self.pod = await self._select_pod()
            try:
                async with self.pod.api.open_websocket(
                    version=self.pod.version,
                    url=f"{self.pod.endpoint}/{self.pod.name}/portforward",
                    namespace=self.pod.namespace,
                    params={
                        "name": self.pod.name,
                        "namespace": self.pod.namespace,
                        "ports": f"{self.remote_port}",
                        "_preload_content": "false",
                    },
                ) as websocket:
                    yield websocket ## HERE DOES NOT BREAK OUT OF THE LOOP
                    break # adding break stopped from continuous yield

            except aiohttp.client_exceptions.WSServerHandshakeError as e:
                self.pod = None
                if connection_attempts > 5:
                    raise ConnectionClosedError("Unable to connect to Pod") from e
                await asyncio.sleep(0.1 * connection_attempts)
```

**Comment by jacobtomlinson** [comment]
Thats great @beanagrammer. Do you have any interest in making a Pull Request to propose that change? It would also be good to try and figure out a minimal reproducible example that can be turned into a test to ensure this doesn't happen again.

**Comment by GeorgeVentura** [comment]
> I was able to track the down the issue for my case.
> 
> After successful ws connection has been made, it does not break out of the loop which causes continuous code execution in _connect_websocket(). `.venv/lib/python3.12/site-packages/kr8s/_portforward.py`
> 
> ```
>     async def _connect_websocket(self) -> None:
>         """Connect to the Kubernetes portforward websocket."""
>         connection_attempts = 0
>         while True:
>             if not self.pod:
>                 self.pod = await self._select_pod()
>             try:
>                 async with self.pod.api.open_websocket(
>                     version=self.pod.version,
>                     url=f"{self.pod.endpoint}/{self.pod.name}/portforward",
>                     namespace=self.pod.namespace,
>                     params={
>                         "name": self.pod.name,
>                         "namespace": self.pod.namespace,
>                         "ports": f"{self.remote_port}",
>                         "_preload_content": "false",
>                     },
>                 ) as websocket:
>                     yield websocket ## HERE DOES NOT BREAK OUT OF THE LOOP
>                     break # adding break stopped from continuous yield
> 
>             except aiohttp.client_exceptions.WSServerHandshakeError as e:
>                 self.pod = None
>                 if connection_attempts > 5:
>                     raise ConnectionClosedError("Unable to connect to Pod") from e
>                 await asyncio.sleep(0.1 * connection_attempts)
> ```

This seems to fix #298

**Comment by beanagrammer** [comment]
> Thats great @beanagrammer. Do you have any interest in making a Pull Request to propose that change? It would also be good to try and figure out a minimal reproducible example that can be turned into a test to ensure this doesn't happen again.

Yeah sure, I can put up a pull request this weekend.

**Comment by jacobtomlinson** [comment]
@GeorgeVentura that's great to hear. 

@beanagrammer looking forward to reviewing it!

**Comment by declark1** [comment]
Great, thanks @beanagrammer for the example and proposed fix. Apologies, I have been sick and was unable to timely follow-up with a reproducible example.

**Comment by jacobtomlinson** [comment]
Could I ask someone to make a PR with these changes so I can merge this in for everyone to benefit from?

**Comment by beanagrammer** [comment]
I can make pr tonight. Its just one line of code change. I'll try to make the min test case. I think if you try to connect more than one ws it throws that error.
