### ISSUE TITLE
Failed to patch object

### ISSUE THREAD

**Issue by matteyeux** [kr8s-org/kr8s#337]
### Which project are you reporting a bug for?

kr8s

### What happened?

Hello, I am having an issue patching a new_class object I created. I have this Gateway: 
```yaml
$ k get gw app-gw -oyaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: app
  creationTimestamp: "2024-02-28T17:28:58Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: app-gw
  namespace: app
  resourceVersion: "9079973"
  uid: a69eacd7-8ee1-4e29-9d96-1a2a9c18a4f4
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - test.com
    port:
      name: tls-passthrough
      number: 443
      protocol: TLS
    tls:
      mode: PASSTHROUGH
```

Using kr8s I want to patch it to edit its host from test[.]com to new-host[.]com 
```python
>>> import kr8s; from kr8s.objects import new_class;
>>> new_class(kind="Gateway", version="networking.istio.io/v1beta1", namespaced=True, asyncio=False)
>>> gw = kr8s.get("gw")[0]
>>> gw.raw['spec']['servers'][0]['hosts'][0]
[{'hosts': [['test.com']], 'port': {'name': 'tls-passthrough', 'number': 8443, 'protocol': 'TLS'}, 'tls': {'mode': 'PASSTHROUGH'}}]
>>> patch = gw.raw
>>> patch['spec']['servers'][0]['hosts'][0] = 'new-host.com'
>>> gw.patch([{"op": "replace", "path": "/", "value": patch}], type="json")
>>> gw.raw['spec']['servers'][0]
{'hosts': ['new-host.com'], 'port': {'name': 'tls-passthrough', 'number': 8443, 'protocol': 'TLS'}, 'tls': {'mode': 'PASSTHROUGH'}}
```

But when I run again `k get gw app-gw -oyaml`, the hostname hasn't changed in the object. Am I missing something ?

**Comment by matteyeux** [comment]
Sorry for the late reply, I kept trying to patch my Gateway, and it seems like the problem is the "path" param in the patch command.

Using `path: "/"` it does not work, but doing something like this `gw.patch([{"op": "replace", "path": "/spec", "value": patch['spec']}], type="json")`

Something weird, is that it does not work when running it as a python script (but does patch correctly when I run the commands from python prompt), with a runtime warning :
```
/home/mathieu/run.py:171: RuntimeWarning: coroutine 'APIObject.patch' was never awaited
  collector_gw.patch([{"op": "replace", "path": "/spec", "value": gw_spec}], type="json")
```

**Comment by matteyeux** [comment]
Update : i found this PR https://github.com/kr8s-org/kr8s/pull/340 that seems to fix my issue, updating to latest version fixed the bug, closing, the issue.

Thanks

**Comment by jacobtomlinson** [comment]
Ah yup that makes total sense. Glad things are working for you now.
