### ISSUE TITLE
Support for loading kubeconfig as a dict 

### ISSUE THREAD

**Issue by matteyeux** [kr8s-org/kr8s#357]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

Hello,

What would be nice, is to be allowed to load a kubeconfig as a dict in kr8s.api or something like this

**Comment by jacobtomlinson** [comment]
I'm sure this could be done but I'd be interested to hear more about what use cases you could imagine for this?

In the meantime you could do something like this:

```python
import kr8s, tempfile, yaml

kubeconfig = {...}

with tempfile.NamedTemporaryFile(mode="w+") as tmp:
    yaml.dump(kubeconfig, tmp)
    tmp.flush()
    api = kr8s.api(kubeconfig=tmp.name)
```

**Comment by matteyeux** [comment]
I download the kubeconfig from an API that returns it as a json file. And the code that downloads and loads the kubeconfig in kr8s runs in a pod. 

I am already writing it on disk, but to improve the pod's security I'd like to make the pod's FS read-only.

**Comment by jacobtomlinson** [comment]
I would expect `tempfile.NamedTemporaryFile()` to write to an in-memory `tmpfs` filesystem so there should be no issue with making the Pod's filesystem read-only.

That being said I'd be fine with making any place we take the `kubeconfig=` keyword accept a dict as well as a path. Do you have any interest in making a PR to implement this?

**Comment by matteyeux** [comment]
Hi, thank you for adding this feature request, I started working on [it](https://github.com/matteyeux/kr8s/commits/main/) but it seems like you did a better job

**Comment by jacobtomlinson** [comment]
Ah sorry I didn't mean to preempt your effort. I really appreciate you taking the time. I was working on a separate issue #360 and found it useful to set the kubeconfig as a dict in a test, so thought I'd just finish it off and expose that all the way up to the `kr8s.api()` call to also close this issue.
