### ISSUE TITLE
Fails to load KubeConfig if "clusters" is null

### ISSUE THREAD

**Issue by damiondoesthings** [kr8s-org/kr8s#358]
### Which project are you reporting a bug for?

kr8s

### What happened?

Hi, I discovered this bug using Dask with Kubernetes from within a K8S pod.

In the pod I set up kubectl by running
`kubectl config set-context dask --namespace=my-namespace && kubectl config use-context dask`

this results in this kubeconfig:

```yaml
apiVersion: v1
clusters: null
contexts:
- context:
    cluster: ""
    namespace: my-namespace
    user: ""
  name: dask
current-context: dask
kind: Config
preferences: {}
users: null
```

Which works fine, i.e. all kubectl commands work as expected. However exuting code, which uses kr8s I run into an exception in `KubeAuth._load_kubeconfig`

```python
>>> await KubeAuth()._load_kubeconfig()
File ~/path/.venv/lib/python3.11/site-packages/kr8s/_auth.py:110, in KubeAuth._load_kubeconfig(self)
    108     self._context = self.kubeconfig.contexts[0]["context"]
    109     self.active_context = self.kubeconfig.contexts[0]["name"]
--> 110 self._cluster = self.kubeconfig.get_cluster(self._context["cluster"])
    111 self._user = self.kubeconfig.get_user(self._context["user"])
    112 self.server = self._cluster["server"]

File ~/path/.venv/lib/python3.11/site-packages/kr8s/_config.py:115, in KubeConfigSet.get_cluster(self, cluster_name)
    113 def get_cluster(self, cluster_name: str) -> Dict:
    114     """Get a cluster by name."""
--> 115     for cluster in self.clusters:
    116         if cluster["name"] == cluster_name:
    117             return cluster["cluster"]

File ~/path/.venv/lib/python3.11/site-packages/kr8s/_config.py:133, in KubeConfigSet.clusters(self)
    131 @property
    132 def clusters(self) -> List[Dict]:
--> 133     clusters = [cluster for config in self._configs for cluster in config.clusters]
    134     # Unpack and repack to remove duplicates
    135     clusters = list_dict_unpack(clusters, "name", "cluster")

File ~/path/.venv/lib/python3.11/site-packages/kr8s/_config.py:133, in <listcomp>(.0)
    131 @property
    132 def clusters(self) -> List[Dict]:
--> 133     clusters = [cluster for config in self._configs for cluster in config.clusters]
    134     # Unpack and repack to remove duplicates
    135     clusters = list_dict_unpack(clusters, "name", "cluster")

TypeError: 'NoneType' object is not iterable
```

This is using kr8s version 0.14.2, python 3.11.8 on Debian Bookworm.

Hope the report helps getting this fixed, thanks!

**Comment by jacobtomlinson** [comment]
Thanks for raising this. In `kr8s` we treat KubeConfig and ServiceAccount authentication as mutually exclusive. I hadn't considered this case where you have a partial KubeConfig to hold some settings but still make use of the ServiceAccount credentials.

Looks like we need up date the authentication to handle this case.

In the meantime I would suggest that you delete the `.kube/config` file you created and set the namespace via your Dask config instead.

```bash
$ dask config set kubernetes.namespace my-namespace
```

**Comment by damiondoesthings** [comment]
Great work! Thanks for fixing

**Comment by jacobtomlinson** [comment]
@damiondoesthings you should be able to upgrade `dask-kubernetes` and `kr8s` to the latest release which will contain this fix.
