### ISSUE TITLE
dependency spec for anyio should be "anyio>=4.0" because implicitly required for httpx-ws >= 0.5.1

### ISSUE THREAD

**Issue by marcodlk** [kr8s-org/kr8s#370]
### Which project are you reporting a bug for?

kr8s

### What happened?

Using anyio < 4.0 results in an error inside httpx-ws function:

```
  File "/[...]/.venv/lib/python3.9/site-packages/httpx_ws/_api.py", line 558, in __init__
    self._send_event, self._receive_event = anyio.create_memory_object_stream[
TypeError: 'function' object is not subscriptable
```

This is due to breaking change in anyio 4.0 where a lot of the functions are now generic classes to better support typing, which httpx-ws is leveraging. The dependency spec for anyio should probably be updated accordingly.

**Comment by jacobtomlinson** [comment]
It looks like `httpx-ws` fixed their lower bound in `0.5.2` so it probably makes more sense to bump that rather than `anyio` as it's actually `httpx-ws` that requires that minimum version.

https://github.com/frankie567/httpx-ws/blob/b2135792141b71551b022ff0d76542a0263a890c/pyproject.toml#L80
