### ISSUE TITLE
Better typing support

### ISSUE THREAD

**Issue by marcodlk** [kr8s-org/kr8s#381]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

First of all, thank you for creating `kr8s` - I completely I agree with the stated motivation and was excited when I found it.

The only thing that's really missing currently in my view is the lack of typing support. From what I gather, the difficulty in trying to provide better typing support stems from the current design aiming to make a "mirrored" sync and async API available via `kr8s.api` and `kr8s.asyncio.api`. I am wondering if it would be possible to keep everything the same from the user's POV but refactor the internal design to allow for full typing support, at least for API objects and methods that users interact with.

The main issue right now imo is that the main sync API objects have no typing support. For instance, the following results in pod always being recognized as `Any`:
```python
from kr8s.objects import Pod

pod = Pod("kube-apiserver", namespace="kube-system")

# Assisting type checker does not work, `pod` is still recognized as `Any`
pod: Pod = Pod("kube-apiserver", namespace="kube-system")
```

When trying to use `kr8s`, I ended up using `kr8s._object` instead of `kr8s.object` in imports when writing code to at least get the type checker to recognize methods and attributes. I would then switch the imports back to the real ones (`kr8s._object`) to run. This is not a good dev experience for users who have become accustomed to typing support.

Would a package like [asyncer](https://asyncer.tiangolo.com/) potentially be helpful here? Is there anything in the current sync + async compat design that needs to be taken into consideration?

I understand this would entail a significant refactor, but it is a bit of a blocker to devs like me, as much as I love everything else about the package. I would be happy to contribute to the refactor if there is an appetite, but it may take some time as I don't have a lot of time to allocate at the moment.

**Comment by jacobtomlinson** [comment]
In #384 I fixed up some of the async wrapping code to make it generic, so the types get passed along correctly. This solves the specific problem being raised in this issue.

My next question is: what's next? What else can we do to improve typing support here?

**Comment by jacobtomlinson** [comment]
The initial problem of not passing types through the async wrapping machinery has been resolved. All `mypy` errors have also been resolved in a series of Pull Requests.

Now that #421 is merged and we are ensuring good type hygiene I think we can close out this issue.

The next step may be to turn on strict mode in `mypy`, but that feels beyond the scope of this issue. If anyone has any other thoughts on improving typing here please feel free to open a new issue.

**Comment by marcodlk** [comment]
Apologies for the delayed response - this looks good, resolves the main problem which was sync API objects having no typing support. Thanks @jacobtomlinson!
