### ISSUE TITLE
Missing `py.typed` file for type-checkers

### ISSUE THREAD

**Issue by max-muoto** [kr8s-org/kr8s#440]
### Which project are you reporting a bug for?

kr8s

### What happened?

The lack of a `py.typed` file is needed by [Pyright](https://www.google.com/search?q=pyright&sca_esv=c4a90a45ab46d06a&sca_upv=1&sxsrf=ADLYWIK_oCZWFNlB3mrkri5H9pJn3DfO5g%3A1720370770101&ei=UsaKZtrgBdn8ptQP2P6FoAI&ved=0ahUKEwja0YjFsJWHAxVZvokEHVh_ASQQ4dUDCA8&uact=5&oq=pyright&gs_lp=Egxnd3Mtd2l6LXNlcnAiB3B5cmlnaHQyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEcyBBAAGEdIzAJQwwJYwwJwAHgDkAEAmAEAoAEAqgEAuAEDyAEA-AEBmAICoAIamAMAiAYBkAYIkgcBMqAHAA&sclient=gws-wiz-serp), and possibly other type-checkers, to fully recognize that this library is properly typed, as mandated in [PEP 561](https://peps.python.org/pep-0561/).

**Comment by jacobtomlinson** [comment]
Closed by #441
