### ISSUE TITLE
Make Api.get() use server side filtering

### ISSUE THREAD

**Issue by jacobtomlinson** [kr8s-org/kr8s#486]
### Which project are you requesting an enhancement for?

kr8s

### What do you need?

In #452 we made `APIObject.get()` more efficient by side server side filtering.

It would be nice if we could make the same improvement to `Api.get()`. For example:

```python
import kr8s

pod1, pod2 = kr8s.get("Pod", "pod1", "pod2")
```

In the above example we list all pods, and then filter out just `pod1` and `pod2`. It would be much more efficient to do the filtering on the server side. In #452 we used a field selector to do this, however it looks like it's not possible to do that for multiple resources as it doesn't support the `in` operator.

Looking at `kubectl get pods pod1 pod2` it appears to make two get requests and does server side filtering on each one so that each request only returns one Pod. We probably want to replicate this pattern in `kr8s`.

**Comment by TanyaKansal** [comment]
@jacobtomlinson can I work on this issue?

**Comment by jacobtomlinson** [comment]
@TanyaKansal Sure!

**Comment by jacobtomlinson** [comment]
Thanks for the enthusiasm! We don't assign issues here as it can block other folks from picking it up if you don't manage to get around to it. Please consider the issue yours. The whole repo has the `hactoberfest` label so we shouldn't need to label individual issues.

_To anyone else reading this if more than two weeks have passed and no PR has been raised to close this then consider it available again._
