### ISSUE TITLE
Make port forward local port default to the remote port

### ISSUE THREAD

**Issue by AustinScola** [kr8s-org/kr8s#505]
### Which project are you reporting a bug for?

kr8s

### What happened?

Synchronous port forwards do not appear to be working. It looks like it is b/c the the start method tries to use run `run_forever` in a thread. but `run_forever` is async:
```python3
    def start(self):
        """Start a background thread with the port forward running."""
        self._bg_thread = threading.Thread(target=self.run_forever, daemon=True)
        self._bg_thread.start()
```

**Comment by AustinScola** [comment]
Hmm, nvm seems to be working I was just missing the local port (which I thought would default to the remote port).

**Comment by jacobtomlinson** [comment]
Maybe we should rename this issue to "Make port forward local port default to the remote port".

Could you share a code example of exactly the snippet you are using so we can reproduce the same result and write a test for the fix?

**Comment by AustinScola** [comment]
Sure, the snippet was roughly this:
```
svc: str = ...
remote_port: int = ...
svc = Service.get(self.svc)
port_forward = svc.portforward(remote_port=remote_port)
port_forward.start()
```

I think k8s defaults to having the local port be the same as the remote port but I could be wrong?

**Comment by jacobtomlinson** [comment]
So I've done a quick check locally with `kubectl` and observed the following behaviour.

```bash
# Start a Pod that is exposing a port
kubectl run nginx --image nginx --port 80

# Port forward and only specify the remote port
kubectl port-forward po/nginx 80
# This binds remote port 80 to port 80 locally

# Port forward and specify an empty local port
kubectl port-forward po/nginx :80
# This binds to a random port locally

# Port forward and specify a local port
kubectl port-forward po/nginx 8080:80
# This binds to port 80 locally
```

So the current behaviour in `kr8s` is the same as `kubectl port-forward po/nginx :80`. It's not clear to me whether we want to switch that to the `kubectl port-forward po/nginx 80` behaviour.

**Comment by jacobtomlinson** [comment]
After thinking on this a bit I feel if the `local_port` argument is completely omitted it should match the `kubectl` behaviour of using the `remote_port`. Then if it is explicitly set to `None` it should choose a random high port.

I've opened #506 to fix this.
